# Copyright 2026 The RabbitSNARK Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Tests for Groth16 verification of gnark-generated proofs.

Verifies a proof produced by the Go gnark prover against a verification key
loaded from the binary export.  This tests cross-prover compatibility: a
proof generated by gnark (Go) is verified by groth16-zorch (Python).

Uses the tiny_multiply fixture (x × x == y, x=3, y=9):
    4 wires, 2 constraints, domain_size=2
"""

from __future__ import annotations

import json
from pathlib import Path

from absl.testing import absltest

from groth16_zorch.gnark import load_gnark_export
from groth16_zorch.groth16.verifier import VerificationKey, verify


class TestGnarkGroth16Verify(absltest.TestCase):
    """Tests for verifying gnark-generated proofs."""

    def setUp(self):
        self.data_dir = Path(__file__).parent / "data" / "tiny_multiply"
        self.data = load_gnark_export(self.data_dir)
        self.vk = VerificationKey.from_gnark(self.data)

        with open(self.data_dir / "proof.json") as f:
            self.proof_json = json.load(f)
        with open(self.data_dir / "public.json") as f:
            self.public_signals = json.load(f)

    def test_valid_proof(self):
        """A gnark Go-generated proof verifies successfully."""
        self.assertTrue(verify(self.vk, self.proof_json, self.public_signals))

    def test_tampered_public_signal(self):
        """Tampering with a public signal makes verification fail."""
        tampered = list(self.public_signals)
        tampered[-1] = "99"  # change Y from 9 to 99
        self.assertFalse(verify(self.vk, self.proof_json, tampered))

    def test_tampered_proof_point(self):
        """Tampering with a proof point makes verification fail."""
        tampered_proof = dict(self.proof_json)
        tampered_proof["pi_a"] = ["1", "2", "1"]
        self.assertFalse(verify(self.vk, tampered_proof, self.public_signals))


if __name__ == "__main__":
    absltest.main()
